### ISSUE TITLE
Selector Order can break nodes

### ISSUE THREAD

**Issue by vipero07** [snabbdom/snabbdom#157]
If you use something like h('input#text-in.item') it results in a different output than h('input.item#text-in').

Expected in both cases and result of h('input#text-in.item'):
`<input class="item" id="text-in" />`

Result from h('input.item#text-in'):
`<input.item id="text-in" />`

**Comment by caesarsol** [comment]
Yes, you are supposed to put the id before the class. That would be a good idea in any case, so I think it is by design :)

**Comment by mightyiam** [comment]
I feel certain that this is by design. Please note that if you're generating the selector's classes based on some conditions, then you'd probably be better off using the [class module](https://github.com/snabbdom/snabbdom#the-class-module) for the classes. And if you're doing the same for the ID, then you'd likely be better off using the [attributes module](https://github.com/snabbdom/snabbdom#the-attributes-module).
