### ISSUE TITLE
Proposal: can we transfer snabbdom to Cycle.js org?

### ISSUE THREAD

**Issue by staltz** [snabbdom/snabbdom#164]
Hi @paldepind and contributors,

As many of you know, we (= @TylorS and I) use and depend heavily on `snabbdom` in http://cycle.js.org. It's a very handy virtual DOM library that keeps to its promise of being: damn fast, small, with a functional API and decent hook system. Previously, we were using `virtual-dom`, which was also good, but not as fast, not as small, not so functional API.

However, one of the main reasons why we migrated from virtual-dom to snabbdom is that that library was largely unmaintained. The core authors didn't have time to merge PRs, manage issues, make new developments. It was rotting, and it was sad. Snabbdom seemed more maintained at that time.

This time, unfortunately, we feel that Snabbdom is rather unmaintained too. Or at least we feel like we could move much faster if Snabbdom as a repository would receive faster issue management and PR merging and authoring, etc. For instance, Tylor forked snabbdom to write https://github.com/TylorS/snabbdom-ts and then again to write https://github.com/TylorS/flow-dom.

So, here's a proposition: **to transfer this snabbdom repo over to the cyclejs org**. And to calm the nerves, here are the terms:
- Tylor and I would actively maintain it (meaning: handling issues, PRs, basic janitoring)
- Paldepind would still be *the* contributor, would still have all the same access rights
- Tylor and I would proceed to make https://github.com/paldepind/snabbdom/issues/150 happen
- Tylor and I would experiment with immutable APIs for snabbdom, like https://github.com/TylorS/flow-dom
- None of the above must drastically affect snabbdom performance or size (unless it's an improvement)

I can totally understand if you don't want to do this. In that case, we would fork snabbdom and make a virtual DOM library mostly compatible with snabbdom, but with the changes mentioned above. That would be ok, but it would be, well... a fork. And if the community can avoid a fork, that's better so there's less confusion, and less scattering of open source workforce.

What do you think?

**Comment by grimalschi** [comment]
Hi, @staltz !

Maybe good idea is to add you and Tylor to maintainers of this repo?

**Comment by acstll** [comment]
Whatever @paldepind decision ends up being, you (contributors) can count on the helper package [`snabbdom-to-html`](https://github.com/acstll/snabbdom-to-html) to be there as well. Whatever helps the community best.

: )

**Comment by paldepind** [comment]
I can certainly see where you are coming from. When building a framework such as Cycle it is of course very important that the packages you depend on are reliable so that you're never stuck because a third party dependency isn't moving along fast enough. And while I wouldn't call Snabbdom unmaintaned I am certainly handling the maintenance at a very slow pace. I think that you and @TylorS offering to help maintain Snabbdom is great news for Snabbdom. I hold both of you in high regard and am certain that your contributions would be beneficial to Snabbdom and it's overall health.

I am happy that Snabbdom is useful to Cycle. I think Cycle is a great framework. When I created Snabbdom my hopes where excactly that people would find it useful for building their own things on top. And several people has done so which is nice. It is important to me that Snabbdom can continue to serve people in this respect. I.e. not only serve Cycle but other users as well. I feel that moving Snabbdom to the Cycle organization might end up implying to some people that Snabbdom is a virtual DOM library just for Cycle. And not an independent virtual DOM library for everyone, whatever you might want to do.

Thus instead of moving Snabbdom to the Cycle org I think it might be a better idea to set up a GitHub organization specifically for Snabbdom. If the respective authors are interested they'd be invited to move their Snabbdom related packages to this organization. For instance @acstll's snabbdom-to-html, snabbdom-jsx, snabbdom-helpers, babel-snabbdom-jsx, and [the other Snabbdom related projects](https://www.npmjs.com/search?q=snabbdom). I, @staltz, @TylorS and the interested related packages owners would be part of this organization and maintain Snabbdom together.

I feel like this would be a great move both for Cycle who can be certain that Snabbdom is timely maintained and for the rest of the Snabbdom users who would still be certain that Snabbdom remains a general purpose virtual DOM library. Additionally it would help me fell less guilty for not dedicating enough time to maintaince :sweat_smile: 

Something completely different: This is the first time I've heard about flow-dom. Is there somewhere where I can read more about it?

**Comment by acstll** [comment]
While I think moving Snabbdom to the Cycle.js org would be great, I like @paldepind idea better. In the end we want things to move forward. I'll be happy to have my package join a Snabbdom org and make it better with your help.

**Comment by syaiful6** [comment]
i can't wait the #150 happen. I check @TylorS repo, and i think it should merge here somehow (maybe just create a branch for it).

**Comment by TylorS** [comment]
@paldepind I think that's a wonderful idea. 

Regarding flow-dom it was an experiment to see if the mutation used heavily in snabbdom could be avoided by using recursion instead of while loops and by having hooks/modules return a new VNode instead of mutating the current. It works to some extent, but it definitely has issues at present. I'm also rather certain than if and when fixed, it'd be rather slow because there are so many extra object being created. If you're interested, I'd be happy to talk about it

**Comment by staltz** [comment]
> Thus instead of moving Snabbdom to the Cycle org I think it might be a better idea to set up a GitHub organization specifically for Snabbdom.

Sure. It didn't even cross my mind that it was an option, but now it seems even more reasonable than moving to Cycle.js org.

Let's do it?

**Comment by paldepind** [comment]
I've created the organization and sent out invitations 😄

**Comment by bloodyKnuckles** [comment]
I'm glad to move https://github.com/bloodyKnuckles/snabbdom-template to the snabbdom org. May I have an invite?

**Comment by staltz** [comment]
Issue seems done. I'll start contributing and putting things in shape probably in October when I get some time.

**Comment by paldepind** [comment]
@bloodyKnuckles Indeed you may :smile:

**Comment by staltz** [comment]
@paldepind another small but essential request: @TylorS and I need *write* access to this repo in order to merge pull requests and whatnot. :)

And in npm, we could be added as contributors: `cycle` and `tylors`.

When it comes to making decisions and consensus, we could setup https://lgtm.co/ on this repo so that at least 2 people need to give a thumbs up to a PR before it can be merged.

**Comment by paldepind** [comment]
Yes. Of course. I've added both of you :)

https://lgtm.co/ looks cool. I've never heard of it. I'm not sure if setting it up is worth it though.

**Comment by staltz** [comment]
Thanks! Soon contributing

**Comment by acstll** [comment]
On another matter, I got some ideas for a logo for `snabbdom`, but I need to work on them before sharing anything. Is that something you'd be interested in @paldepind ?

**Comment by paldepind** [comment]
@acstll I've actually given a logo some thought but without coming up with any good ideas. If you have the good ideas I think that would be totally awesome!

**Comment by acstll** [comment]
Alright! I'm gonna give it a try then. 😃

**Comment by paldepind** [comment]
I'm looking forward to seeing that. Feel free to open an issue related to the logo :smile:

**Comment by AlexGalays** [comment]
Hello! Something else that was done on top of snabbdom:  https://github.com/AlexGalays/kaiju

**Comment by paldepind** [comment]
Nice. I've sent you an invite @AlexGalays :smile: Please open issues about those issues. I see your point with regards to the `create` hook.
