### ISSUE TITLE
Order independent diff

### ISSUE THREAD

**Issue by aman-tiwari** [snabbdom/snabbdom#202]
As an enhancement, it would be cool if there was some way to say "don't care about the order of the children of this node when diffing", which would mean that if only some of the node's children are modified, but the list of children is in a different order, it won't trigger a re-render of the whole list of children.

My use case for this is pretty unusual, using snabbdom as a virtual dom for [aframe](https://github.com/aframevr/aframe/), where the order of elements doesn't matter and view creation is very expensive, but there should be other use-cases too (e.g whenever the view's position/other styling isn't dependent on its order).

Perhaps this mode could be enabled by passing in a object like `{ uniqKeyForView1 : child1, uniqKeyForView2: child2}`, such that if in the subsequent patch if `uniqKeyForView1` is present `child1` won't be rerendered.

**Comment by nunocastromartins** [comment]
I realise this issue is quite old. In any case, I couldn't quite understand your request:

> if only some of the node's children are modified, but the list of children is in a different order, it won't trigger a re-render of the whole list of children.

I don't understand what you mean by "rerender the whole list of children". Could you give us an example? If I understand correctly you mean that if you have:
```js
var vNode1 = h('div', [
  h('i', {key: 1}, "foo"),
  h('i', {key: 2}, "bar")
]);
```
resulting in:
```html
<div>
  <i>foo</i>
  <i>bar</i>
</div>
```
and patch it against:
```js
// Change order of children and change the content of one of them
var vNode2 = h('div', [
  h('i', {key: 2}, "hello"),
  h('i', {key: 1}, "foo")
]);
```
You'd want the final result to be:
```html
<div>
  <i>foo</i>
  <i>hello</i>
</div>
```
Is that it? I.e. you'd want the content of the elements to be updated, but not their order, because it doesn't matter?

If this is indeed the behaviour you'd want and, if in fact the order doesn't matter, you could always sort the list of children before every repatch. That would make the patching algorithm "ignore the order", as it would always be consistent. Would that be too expensive as well?

**Comment by kuraga** [comment]
#95 and #143 could help?

**Comment by mightyiam** [comment]
I'm going to be bold and close this issue and suggest what @nunocastromartins before me suggested. Perhaps, If you don't care about the order, then keep the order consistent, and you'd minimize mutations. If this is insufficient for anyone, please comment.
