### ISSUE TITLE
[Discussion] ambiguity between default export and named exports

### ISSUE THREAD

**Issue by caridy** [snabbdom/snabbdom#225]
I'm not sure about reason to have everything exported as a default export and a corresponding named export (I could not find a discussion around that decision), but I hope that can be revisited. In general, the way we designed the ESM was to avoid such as ambiguity. In theory, there is no problem with exporting the same thing using multiple names (including default), but in practical terms, there are:

* any consumer trying to do detection may fail (this is the case of `rollup`, if you try to `import` or `require` `snabbdom` from a project that relies on the popular rollup bundler, it will fail because rollup applies detection to normalize the exports by testing against the `default` export, assuming regular CJS modules will not have them, and transpiled CJS will have them but with the namespace object.
* we have enough issues with CJS and modules (which we are trying to solve via few actives initiatives at TC29 and Node CTC), we have arrived to the conclusion that the lower common denominator is to let transpilers (babel and ts) to compiled ESM to a simple CJS module. Last time we spoke to TS folks, they were onboard with this idea, I'm not sure why snabbdom needs the complexity of the duplicated entries after adopting TS.
* Last, but not least, it is very confusing for the consumer, having a CJS that contains two values, default and named export with the same thing (`require('snabbdom/h').default === require('snabbdom/h').h`.

Can someone explains the reasons of the duplication? I see a few options:

* refactor to either use the default export only or the named export only (I think named exports are just fine for snabbdom).
* try to work with TS folks and rollup folks to make these ambiguous modules compiled with TS to work with rollup.

@DanielRosenwasser, @Rich-Harris can you guys chime on this?

**Comment by TylorS** [comment]
I'm also definitely in favor of named exports only :)

A couple of reasons I can think of off the top of my head

1. Using a default export can lead to inconsistent naming ( maybe trivial ). Imagine a development team of 10 or more people, and if even 1 of those people decide to change the name of the default export for any reason in something they are working on it will not be immediately obvious to any of the other developers. e.g.
  ```typescript
    // developers 1-9
    import foo from 'my-library'
    // developer 10
    import bar from 'my-library'
  ```
Again, this may be trivial, but smaller things can lead to confusion between many people with different levels of skills and knowledge. Named exports remedy this issue by always requiring users to explicitly rename an export if they wish to use different name. e.g. `import { foo as bar } from 'my-library'` thus avoiding any confusion on where a value comes from.

2. Mixing default exports and named exports lead to inconsistent builds across most (if not all) bundlers such as rollup. The mixing of default exports will lead to commonjs users to (unexpectedly) need to use `require('my-libary').default` rather than the expected `require('my-library')`. This is generally done by bundlers because if your default export is a function, and your named exports are appended to this function you will immediately take performance hits as JS engines (at least V8) will de-optimize the affected functions.

3. For those of us who use TypeScript (we do provide type defintions BTW) when there are default exports it is impossible to create type definitions that work with *both* commonjs and also ES2015 modules due to language limitations.

**Comment by Rich-Harris** [comment]
With the caveat that I don't know any of the context here, in the general case I strongly agree with @caridy and @TylorS that having both named and default exports pointing to the same thing is a bad idea. I've seen lots of cases where that sort of thing led to all sorts of avoidable interop headaches.

**Comment by acstll** [comment]
What do you think about this approach?

The **main module** should have only named exports and have almost everything in there, so you can do:

```js
import { init, h, modules, thunk } from 'snabbdom'
```

and then, **submodules** should be only default:

```js
var h = require('snabbdom/h')
var init = require('snabbdom/init')
// etc…
```

the latter aimed at people using CJS (and good ol' browserify), here tree-shaking isn't even needed since you're already `require`ing only what you need.

**Comment by staltz** [comment]
> in favor of named exports only

Yeah I think so too, I can't come up with a good argument for default exports.

> and then, submodules should be only default:
> `var h = require('snabbdom/h')`

Actually for CJS it would be `require('snabbdom/h').default`.

**Comment by paldepind** [comment]
@caridy 

> I'm not sure about reason to have everything exported as a default export and a corresponding named export (I could not find a discussion around that decision), but I hope that can be revisited.

This happened when Snabbdom was ported to TypeScript in #193. The rationally was that it allowed people to do the import in the way that is most convenient to them. But you bring up some very good arguments as for why that wasn't such a good idea.

I think we should used named exports only. I don't particularly fancy the default export feature and the problematic way in which it transpiles.

1. Remove all the default exports.
2. Rename `src/snabbdom.ts` to `src/init.ts`
3. Add a new main file `src/snabbdom.ts` that re-exports all the commonly used modules (`init`, `h`, `style`, etc.).

This will of course be a breaking changes but should fix the issues brought up by @caridy and improve the user ergonomics as suggested by @acstll by having a main file that is more convenient.

**Comment by kuraga** [comment]
Hm. And which is the current way to import (and using) using ESM?.. For example, `h`?

**Comment by acstll** [comment]
I believe `esm` is for Node.js.

Using Webpack 4, a regular named import should work (I just tested it):

```js
import { h } from 'snabbdom'
```

**Comment by mightyiam** [comment]
Thanks to everyone for the input. Closing in favor of #522 and #523.
