### ISSUE TITLE
Filter out null/undefined children

### ISSUE THREAD

**Issue by staltz** [snabbdom/snabbdom#226]
In Cycle.js we roll our own hyperscript just for one reason: we filter out falsy (null or undefined or empty string) children. This is the only modification we do compared to snabbdom's hyperscript:

```diff
 h(sel: string, b?: any, c?: any): VNode {
  let data = {};
  let children: Array<VNode | string> | undefined;
  let text: string | undefined;
  if (arguments.length === 3) {
    data = b;
    if (is.array(c)) {
      children = c;
    } else if (is.primitive(c)) {
      text = c as string;
    }
  } else if (arguments.length === 2) {
    if (is.array(b)) {
      children = b;
    } else if (is.primitive(b)) {
      text = b as string;
    } else {
      data = b;
    }
  }
  if (is.array(children)) {
+   children = children.filter(x => !!x);
    for (let i = 0; i < children.length; ++i) {
      if (is.primitive(children[i])) {
        children[i] = vnode(undefined as any, undefined, undefined, children[i] as any, undefined);
      }
    }
  }
  if (sel[0] === 's' && sel[1] === 'v' && sel[2] === 'g') {
    addNS(data, children, sel);
  }
  return vnode(sel, data, children, text, undefined);
};
```

We're considering moving this change to snabbdom itself. So, question: are there any strong reasons not to do this?

**Comment by nunocastromartins** [comment]
I'm just going to raise a few questions here, but I'm actually leaning against your proposal in favour of something else. Consider:
```js
let children = [h('i', 0), null, h('i', 2)];
let parent = h('div', children);
parent.children.length === children.length; // I'd say this should hold

// I'd also like to be able to do this:
patch(parent.children[1], h('i', 1));
```
I'm not sure whether Snabbdom is _supposed_ to be used like this, but this would allow you to patch a single child without patching the whole `parent`. I'd prefer if Snabbdom rendered `null`/`undefined` values as some "placeholder" node that could afterwards be patched (I'm not actually sure, but I don't think it currently does this) - I'd say render them as empty text nodes.

Your approach does, however, have a thing I appreciate. I don't know if it's done on purpose but, by calling `children.filter`, you're actually creating a new array. This is good because afterwards the original array isn't changed!

```js
let children = [0, 1, 2];
let node = h('div', children);
console.log(children[1]); // What should this print?
```
The same question can be asked about the data: when adding a namespace, Snabbdom actually manipulates the original object, what if I'm sharing the same data object between different nodes, one of them an `svg` element, another a `div`? Maybe I should open a new issue with this. :-)

Returning to the original issue, what is the reason (in Cycle.js) for filtering the children array, and would it be solved by mapping them to empty text nodes instead?

**Side note:** your `!!x` code is filtering out the number `0`, is it supposed to do that? At least I'm pretty sure that in Snabbdom, if you guys opt to move forward with the filtering option, this shouldn't happen (as the number `0` should be mapped to a text node)!

**Comment by staltz** [comment]
> Returning to the original issue, what is the reason (in Cycle.js) for filtering the children array

Because this test (not in the suite right now) fails, snabbdom breaks when it hits a null:

```js
it('supports some null children', function() {
  var vnode1 = h('span', [
    h('span', 'hi'),
    h('span', 'snabbdom')
  ]);
  var vnode1 = h('span', [
    h('span', 'hi'),
    null,
    h('span', 'snabbdom')
  ]);
  elm = patch(vnode0, vnode1).elm;
  assert.equal(elm.children.length, 2);
  elm = patch(vnode1, vnode2).elm;
  assert.deepEqual(map(inner, elm.children), ['hi', 'snabbdom']);
});
```

With:

```
TypeError: Cannot read property 'data' of null
    at createElm (browserified.js:1907:28)
    at createElm (browserified.js:1930:42)
    at patch (browserified.js:2123:13)
    at Context.<anonymous> (browserified.js:2588:17)
```

> and would it be solved by mapping them to empty text nodes instead?

It would be solved, but that is something that would require people using the framework to update their code, it'd be a breaking change, and I think it's better if we can avoid breaking changes.

> Your approach does, however, have a thing I appreciate. I don't know if it's done on purpose but, by calling children.filter, you're actually creating a new array. This is good because afterwards the original array isn't changed!

Actually the solution doesn't need to be `Array.filter`, as long as nulls and undefined are somehow filtered out. In fact I believe there is a more efficient way to filter out.

> Side note: your !!x code is filtering out the number 0, is it supposed to do that?

That's a valid point, and a bug in Cycle.js. It's like this because only recently did snabbdom start supporting numbers as children.

**Comment by acstll** [comment]
I'm in favor of filtering them out without cloning the array (to be consistent). Whenever I would pass `null` I'd mean "nothing", and it's usually something like `foo ? renderFoo() : null`. If I wanted an empty text node I could do `foo ? renderFoo() : ''`.

**Comment by nunocastromartins** [comment]
I think you can simply change the [`updateChildren`](https://github.com/snabbdom/snabbdom/blob/master/src/snabbdom.ts#L165) function to ignore `null` values, then. It currently ignores `undefined` values, doesn't it? Wouldn't it work simply by changing:
```js
    ...
    while (oldStartIdx <= oldEndIdx && newStartIdx <= newEndIdx) {
      if (isUndef(oldStartVnode)) {
        oldStartVnode = oldCh[++oldStartIdx]; // Vnode has been moved left
      } else if (isUndef(oldEndVnode)) {
        oldEndVnode = oldCh[--oldEndIdx];
      } ...
```
to:
```js
    ...
    while (oldStartIdx <= oldEndIdx && newStartIdx <= newEndIdx) {
      if (oldStartVnode == null) {
        oldStartVnode = oldCh[++oldStartIdx]; // Vnode has been moved left
      } else if (oldEndVnode == null) {
        oldEndVnode = oldCh[--oldEndIdx];
      } ...
```
I didn't test this, but something like this _should_ work, I believe.

**Comment by nunocastromartins** [comment]
**Regarding my previous comment:**

> I think you can simply change the updateChildren function to ignore null values, then.

It was slightly more complicated. :-)

> It currently ignores undefined values, doesn't it?

Actually it doesn't, my bad. My PR makes it ignore them, though.

**Comment by paldepind** [comment]
> So, question: are there any strong reasons not to do this?

I don't think so 😄 And putting inside Snabbdom allows for solutions like @nunocastromartins's PR that should perform better than using `filter`.

**Comment by ornicar** [comment]
Does it mean that `h` signatures should be updated from `children: Array<Node>` to `children: Array<Node | undefined>`?

https://github.com/snabbdom/snabbdom/blob/b98f5a91a254a11e7d58e530988d5e77e0c8d737/src/h.ts#L21

**Comment by staltz** [comment]
Yeah, `Array<VNode | undefined | null>`
