### ISSUE TITLE
Various props of VNode are typed `any`

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#264]
https://github.com/snabbdom/snabbdom/blob/v0.6.7/src/vnode.ts#L16-L23

Would it be beneficial to type those?

**Comment by staltz** [comment]
Their possible values are so wide that it doesn't make sense to type. What would you do with `dataset` for example?

**Comment by paldepind** [comment]
> Would it be beneficial to type those?

I definitely think it would.

At the very least they could be typed using index signatures. That would prevent stuff like giving `style` a `number`.

There are other opportunities as well. The `on` property could be typed like this:

```ts
export type On = {[N in HTMLElementEventMap]: (ev: HTMLElementEventMap[N]) => any}
```

This would both ensure that they keys in the `on` object are valid event names and figure out the specific event type that the event handler will receive.

The above doesn't handle that the values in the `on` object can also be arrays but it could be expanded to handle that as well.

The `style` property could be defined like this:

```ts
type StyleMap = Partial<CSSStyleDeclaration>;
const Style = StyleMap & {delayed: StyleMap, remove: StyleMap};
```

However, the above would disallow setting CSS variables like this `{style: {'--warnColor': 'yellow'}}`. So we'd probably have to add an index signature as well.

**Comment by nunocastromartins** [comment]
> However, the above would disallow setting CSS variables like this {style: {'--warnColor': 'yellow'}}. So we'd probably have to add an index signature as well.

Or create a new module to handle custom properties. With the added benefit that you could drop the `--` syntax: `{customProps: {warnColor: 'yellow'}}`.

**Comment by mightyiam** [comment]
I submitted a pull request as #271. Please see if it helps.

**Comment by TylorS** [comment]
`props` in particular could be improved quite a bit further. Here is an interface containing all Node/Element/HTMLElement properties I could find on MDN.

```typescript
export interface HtmlProperties {
  // Node properties
  nodeValue?: string | null;
  textContent?: string | null;

  // Element properties
  className?: string;
  id?: string;
  innerHTML?: string;
  scrollLeft?: number;
  scrollTop?: number;
  slot?: string;

  // HTML Element specific
  abbr?: string;
  axis?: string;
  accessKey?: string;
  accept?: string;
  acceptCharset?: string;
  action?: string;
  align?: string;
  aLink?: any;
  allowFullscreen?: boolean;
  alt?: string;
  altHtml?: string;
  archive?: string;
  async?: boolean;
  autocomplete?: string;
  autofocus?: boolean;
  autoplay?: boolean;
  background?: string;
  behavior?: string;
  bgColor?: any;
  bgProperties?: string;
  border?: string;
  borderColor?: any;
  caption?: HTMLTableCaptionElement;
  cellPadding?: string;
  cells?: HTMLCollectionOf<HTMLTableDataCellElement | HTMLTableHeaderCellElement>;
  cellSpacing?: string;
  charset?: string;
  checked?: boolean;
  cite?: string;
  clear?: string;
  code?: string;
  codeBase?: string;
  codeType?: string;
  cols?: string;
  colSpan?: number;
  compact?: boolean;
  content?: string;
  coords?: string;
  contentEditable?: string;
  controls?: boolean;
  crossOrigin?: string;
  currentTime?: number;
  data?: string;
  dateTime?: string;
  declare?: boolean;
  default?: boolean;
  defaultChecked?: boolean;
  defaultMuted?: boolean;
  defaultPlaybackRate?: number;
  defaultSelected?: boolean;
  defaultValue?: string;
  defer?: boolean;
  dir?: string;
  direction?: string;
  disabled?: boolean;
  download?: string;
  draggable?: boolean;
  encoding?: string;
  enctype?: string;
  event?: string;
  face?: string;
  formAction?: string;
  formEnctype?: string;
  formMethod?: string;
  formNoValidate?: string;
  formTarget?: string;
  frame?: string;
  frameBorder?: string;
  frameSpacing?: any;
  hash?: string;
  headers?: string;
  height?: any;
  hidden?: boolean;
  hideFocus?: boolean;
  high?: number;
  host?: string;
  hostname?: string;
  href?: string;
  hreflang?: string;
  hspace?: number;
  htmlFor?: string;
  httpEquiv?: string;
  indeterminate?: boolean;
  innerText?: string;
  isMap?: boolean;
  kind?: string;
  label?: string;
  lang?: string;
  link?: any;
  longDesc?: string;
  loop?: number;
  low?: number;
  lowsrc?: string;
  marginHeight?: string;
  marginWidth?: string;
  max?: string;
  maxLength?: number;
  method?: string;
  media?: string;
  min?: string;
  minLength?: number;
  multiple?: boolean;
  msAudioCategory?: string;
  msAudioDeviceType?: string;
  msHorizontalMirror?: boolean;
  msKeySystem?: string;
  msPlayToDisabled?: boolean;
  msPlayToPreferredSourceUri?: string;
  msPlayToPrimary?: boolean;
  msRealTime?: boolean;
  msStereo3DPackingMode?: string;
  msStereo3DRenderMode?: string;
  msZoom?: boolean;
  muted?: boolean;
  name?: string;
  noHref?: boolean;
  noResize?: boolean;
  noShade?: boolean;
  noWrap?: boolean;
  noValidate?: boolean;
  object?: string | null;
  optimum?: number;
  outerHTML?: string;
  outerText?: string;
  pathname?: string;
  pattern?: string;
  placeholder?: string;
  playbackRate?: number;
  port?: string;
  preload?: string;
  protocol?: string;
  profile?: string;
  readOnly?: boolean;
  readyState?: number;
  rel?: string;
  required?: boolean;
  rev?: string;
  rows?: string | HTMLCollectionOf<HTMLTableRowElement>;
  rowSpan?: number;
  rules?: string;
  scope?: string;
  scrolling?: string;
  scheme?: string;
  search?: string;
  selected?: boolean;
  selectedIndex?: number;
  selectionDirection?: string;
  selectionEnd?: number;
  selectionStart?: number;
  shape?: string;
  size?: number;
  sizes?: string;
  scrollAmount?: number;
  scrollDelay?: number;
  src?: string;
  srclang?: string;
  srcObject?: MediaStream | null;
  srcset?: string;
  spellcheck?: boolean;
  standby?: string;
  start?: number;
  status?: any;
  step?: string;
  summary?: string;
  target?: string;
  tabIndex?: number;
  tBodies?: HTMLCollectionOf<HTMLTableSectionElement>;
  text?: string;
  tFoot?: HTMLTableSectionElement;
  tHead?: HTMLTableSectionElement;
  title?: string;
  trueSpeed?: boolean;
  type?: string;
  units?: string;
  url?: string;
  urn?: string;
  useMap?: string;
  vspace?: number;
  valueAsDate?: Date;
  valueAsNumber?: number;
  value?: string;
  version?: string;
  volume?: number;
  vAlign?: string;
  vLink?: any;
  webkitdirectory?: boolean;
  width?: number;
  wrap?: string;
}
```

**Comment by caridy** [comment]
@TylorS I'm not sure that list will help us here, it definitely help me with a higher layer (a compiler that we are building for html), but for snabbdom, it doesn't really reference most of those directly in the code, it just assume that keys coming from the `VNodeData` structure, which probably means that don't need to declare them anywhere in this repo. Another aspect of these is that you could choose to reference them as props or attributes, depending on what you're trying to do with snabbdom.

**Comment by TylorS** [comment]
> for snabbdom, it doesn't really reference most of those directly in the code

It's not about what is referenced in snabbdom's code, but how user's interact with it when using TypeScript.
```typescript
h('a', { props: { hrfe: 'http://example.com' } }, [ 'Some link'])
```
would now be a compiler error, rather than a runtime "What's going on?" and some (hopefully easy) debugging.

> Another aspect of these is that you could choose to reference them as props or attribute

HTML properties and attributes are not the same thing, and properties should be favored. 
http://lucybain.com/blog/2014/attribute-vs-property/

**Comment by caridy** [comment]
Ok, there are to main issues to clarify here:

## Issues with Properties

1. Properties are valid or not depending on the element that they are applied to. There is a finite number of global properties. Having a list of all properties give you nothing, if I have `h('div', { props: { href: 'http://example.com' } }, [ 'Some link'])`, should that be an error? `href` is not a global attribute, and does not apply to a `div`, so? Similarely, custom properties for custom elements are important, I might have `h('x-foo', { props: { hrfe: 'http://example.com' } }, [ 'Some link'])` and that is perfectly valid since my web component exposes a public property called `hrfe`.

2. This is even more important that bullet point 1, we should NOT favor properties, at least not today, because there are subtleties that snabbdom doesn't take into consideration. For example, HTML properties are usually non-configurable properties, which means deleting the value has no effect whatsoever, e.g.:
![image](https://cloud.githubusercontent.com/assets/38969/24765428/bc699800-1ac5-11e7-83fa-53ddb12ede6d.png)

I can explain more, and give you more examples, but you get the idea. You could also try to do the same in snabbdom by doing:

```
const vnode1 = h('input', { props: { tabIndex: -1 } });
const vnode2 = h('input', { props: { } });
const input = document.createElement('input');
patch(input, vnode1);
patct(vnode1, vnode2);
```

Of course, this issues doesn't affect attributes.

## Recommendation

Snabbdom should not be in the business of validating what you pass into it, it is a very low level API for others to build on top of. If fact, I will recommend people to create their own `h` instead of using the one we offer, because they can get way better perf if they can have enforcement of what their own `h()` is suppose to produce. The same principle applies to validation, they can validate the objects they produce, we just don't care.

**Comment by caridy** [comment]
Another good example of the issue of making this a binary decision between props and attributes are `checked`, `value`, and other input related attributes that are meant to be used as initializers, but has no effect when the value of them changes after that. In which case a vnode will have to specify them as props. VUE has a well define list of those attributes that must be passed as props, and that schema seems to be working fine for  them. I have been using a similar technique as well, with no issues so far.
