### ISSUE TITLE
Props with falsy values are deleted

### ISSUE THREAD

**Issue by ddivecs** [snabbdom/snabbdom#283]
Description: If a prop has a key that has a falsy value, the key is deleted.

Reproducer: https://jsfiddle.net/0q6uueou/

Affected Browsers: Chrome 42 and prior on windows (possibly others).

Seems due to this if condition: https://github.com/snabbdom/snabbdom/blob/master/src/modules/props.ts#L15

I ran into a problem while debugging snabbdom in older versions of chrome. scrollTop starts at 0, and in chrome 42 and prior you were able to delete scrollTop from an element.

This is still a bug in latest chrome in certain situations, as shown in the reproducer.

**Comment by caridy** [comment]
for those, you can use attributes instead of props for all well-known html attributes. more details about this issue here https://github.com/snabbdom/snabbdom/issues/264#issuecomment-292232037

**Comment by ddivecs** [comment]
I'm not sure i understand. scrollTop is not an attribute, it is exclusively a property.

**Comment by caridy** [comment]
ah, you're right. but still props implementation is all messed up because even if we change that condition, the delete is not useful:

![image](https://cloud.githubusercontent.com/assets/38969/25457386/19774dec-2aa4-11e7-9863-269f95c2c8f3.png)

Aside from that, I don't think using `scrollTop` or any other ephemeral state should be controlled via the vnode state, that seems very tricky due to the nature of the rehydration of the old state. E.g.: the page load, the user is interacting with it (rendered from the server side), when the page rehydrates, the scrollTop gets reset, and now the page jumps again although the user is already engaged in the scrolling action :/, same for cases in which the scroll is disabled, etc... it is just very weird to control that via state rather than a one time operation on the corresponding DOM element directly.

I don't know any solution for this issue ATM.

**Comment by fenduru** [comment]
@caridy manual control of props like `scrollTop` are important when implementing virtualized lists using a vdom. This apparently also causes problems in PhantomJS 2, which was the reason that @yyx990803 [patched this](https://github.com/vuejs/vue/commit/f135891f4d5d19e0b9e52b420e6011008238614f) in Vue.js's fork of snabbdom.

**Comment by caridy** [comment]
@fenduru that might be a good-enough solution, it definitely works for `scrollTop`, but I wonder if setting other props to `undefined` will have unpredictable results. E.g.:

![image](https://cloud.githubusercontent.com/assets/38969/25627774/a1f07ee6-2f18-11e7-93cf-9a7970b0032f.png)

Some people trying to use `className` property will see a bunch of `class="undefined"` in the DOM. I'm not worry about `className` since you can't really use it today with the `delete` either, but the same applies to any property that will be internally casted to string value. We will need more investigation here I think.

**Comment by akirn** [comment]
Any update on this?

**Comment by mightyiam** [comment]
#624
