### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by caesarsol** [snabbdom/snabbdom#286]
@staltz expressed the need for an automated perf benchmark, and I would like to help.
On another PR, @diervo mentioned something about a perf benchmark integration he's working on.

I just wanted to create a centralized information and bikeshedding thread on the topic. 
The questions are:
- What do we know, and what is exactly needed?
- How could the benchmark compare between results?
- Are there any CI tools that could help?
- ~~Which browsers should we target?~~
- There is a benchmarking draft, how is that working?

I'll think about it, in the meantime thanks anybody who could shine some light!

**Comment by staltz** [comment]
Just a quick suggestion: separate perf benchmark from browser compatibility tests. Ideally you want to be able to run the perf benchmarks quite quickly and in node.js. You could maybe even avoid the DOM, since there is htmldomapi. This would mean you can just know whether something got slower or faster.

**Comment by caesarsol** [comment]
That's right, browser compatibility is quite a different task!

(Which will need to be addressed as well in an automated way, if you agree)

**Comment by diervo** [comment]
@caesarsol We have all of that built for an internal project we are working on: It does snapshots between commits and you can compare any two different versions. It has CLI, a standalone runner, a selenium runner, and a bunch of crazy optimizations to be able to remove variability due to GCs, etc, and all the statistical significance built in.

Our plan at Salesforce is to open source it soon (within a couple of months) and integrate it here probably even before that.

**Comment by paldepind** [comment]
> Our plan at Salesforce is to open source it soon (within a couple of months) and integrate it here probably even before that.

That sounds really awesome!

**Comment by mightyiam** [comment]
Started working on this. Here is some initial code. Ideas are most welcome.

```ts
import faker from 'faker';
import { VNode } from '../vnode';
import h from '../h';
import { init } from '../snabbdom';

describe.only('benchmark', () => {
  it('is fast', () => {
    const makeData = () => ({
      name: faker.company.companyName()
    });

    type Company = ReturnType<typeof makeData>;

    const patch = init([]);
    const container = document.createElement('section');
    document.body.appendChild(container);

    const view = (company: Company): VNode => h(
      'section',
      {},
      [
        h(
          'h2',
          company.name
        )
      ]
    );

    new Array(100)
      .fill(null)
      .map(makeData)
      .reduce(
        (acc, data, i): VNode => {
          performance.mark(String(i));
          const vnode = view(data);
          patch(acc, vnode);
          performance.measure(String(i), String(i));
          return vnode;
        },
        container as HTMLElement | VNode
      );
    const durations = performance
      .getEntriesByType('measure')
      .map((measure) => measure.duration);
    const minimumDuration = Math.min(...durations);
    const maximumDuration = Math.max(...durations);
    const averageDuration = durations.reduce((acc, cur) => acc + cur, 0) / durations.length;
    console.log(minimumDuration, maximumDuration, averageDuration);
  });
});
```

**Comment by mightyiam** [comment]
Some more progress. Managed to get the karma test runner to report the benchmark results at the end of the test run. That took a while because I couldn't find documentation for karma's API for reporters. And I may be using a private karma part :sweat_smile:.

The plan is to test in the browsers because of the possibility that performance could be different in different browsers for different reasons. Polyfills and transpilations for one. @staltz I am not ignoring what you suggested regarding running in Node.js. Perhaps if we test performance in all supported browsers, and some of them run V8 then a similar Node.js test would seem redundant.

Part of the design is that for each browser, the CI environment has a variable that represents the maximum time of the performance test run in that browser. If in a certain PR performance regresses above that time for that browser, the performance test would fail. Those variables would be edited manually.

Progress: Got this setup mostly working. The benchmark would be a series of data to view patches, each individually measured and the above mentioned time would be the average of those. If anyone has large view vtree generating function to contribute, along with an interface of the input of that, that would be perfect. Of course, it must be something that is alright to end up as public code.

**Comment by mightyiam** [comment]
Please review #569 .

**Comment by mightyiam** [comment]
> Part of the design is that for each browser, the CI environment has a variable that represents the maximum time of the performance test run in that browser. If in a certain PR performance regresses above that time for that browser, the performance test would fail. Those variables would be edited manually.

This won't be reliable, because it is subject to change of the testing infrastructure between runs. Instead, I will compare the last release with the current branch's code.
