### ISSUE TITLE
Updating only a child in a large vnode/tree

### ISSUE THREAD

**Issue by wbern** [snabbdom/snabbdom#299]
So I realize this may be against the main principle of entrusting differences to the virtual Dom, but on many occasions, I really would prefer to avoid updating 90% of my components and update simply the child that caused the change, reusing all other partial vnodes. 

I tried to accomplish this by directly modifying the vnode I've already applied to the DOM, but realized quickly that I probably need to clone the vnode before I can do this.

Before I venture any deeper in this endeavor, is there any advice you can possibly offer me? Would be very grateful for it!

**Comment by caridy** [comment]
It is not that simple because the old structure (from the parent) holds a reference to the original vnode, which means that if you plan to update the child vnode manually, and eventually update the root vnode, it will be out of sync. I have seen cases where the mutation of the original vnode is ok, but a clone of it is used as the old vnode for the off-cycle mechanism, and that might help.

**Comment by wbern** [comment]
@caridy Thanks for your assistance. I had to do a lot of re-writes today to get snabbdom and snabbdom-pragma to work in my project, but I've arrived at the point where I need to do child vnode manipulation in order to make my components stateful.

If you have any references to previous attempts at this, do let me know. I will report back my findings here tomorrow.

**Comment by nunocastromartins** [comment]
This is tricky.
I do something similar in my (currently private) fork of this library, so let me share my experience.

First of all, this should be difficult (if not impossible) with Snabbdom's current implementation.
It _might_ be possible via a custom module—taking advantage of Snabbdom's hooks—but I gave up on the idea after playing around with it for a while.

So, what is the problem? You might already understand it, but let's recap; as @caridy mentioned:
> the old structure (from the parent) holds a reference to the original vnode, which means that if you plan to update the child vnode manually, and eventually update the root vnode, it will be out of sync

What does this mean? Imagine the following example:
```js
let item1 = h('li', {id: 1}, 'hello')
let item2 = h('li', {id: 2}, 'world')
let list  = h('ul', [item1, item2])
```
Where you want to change the first list item to `h('li', {id: 1}, 'goodbye')`.
You could do:
```js
let newItem1 = h('li', {id: 1}, 'goodbye')
patch(item1, newItem1)
```
And it _would work_; as in: the DOM would be updated.
However, `list` will still maintain a reference to `item1` instead of to `newItem1`: which will likely cause problems if `list` is ever updated.

What did I do to allow updating sub-trees?
I changed the core of Snabbdom.

Currently, Snabbdom works with the notion of **virtual nodes**: which are an abstract representation of element nodes, text nodes, or even comment nodes. I extended Snabbdom to also allow the usage of _references_ to virtual nodes.

This lets us do something similar to the following:
```js
let item1 = ref(h('li', {id: 1}, 'hello'))
let item2 = h('li', {id: 2}, 'world')
let list  = h('ul', [item1, item2])

item1.patchWith(h('li', {id: 1}, 'goodbye'))
```
I made it so that Snabbdom renders the content of a `ref` but, at the same time, I allow patching the content of a `ref` against a new virtual node—keeping everything synchronised. This effectively allows the kind of sub-tree patching you seem to desire.

Is this easy to implement? Well, conceptually it isn't very complicated; but one has to dive into the core of the library.

For multiple reasons (mainly due to the particular way I'm using Snabbdom) this was my approach; I hope the insight is useful.

Again: it _might_ be possible to achieve this using a custom module. Give it a try and let me know!

**On another note:** Have you looked at Snabbdom's [thunks](https://github.com/snabbdom/snabbdom#thunks)? If you're having performance issues, they might be something to look at.

**Comment by wbern** [comment]
@nunocastromartins it sounds indeed quite tricky.. I guess a deep clone will not cut it then, as it sounds like snabbdom will keep trying to reference the old and "outdated" vnode inside its entire vnode tree.

It feels like a big drag on performance for me to have to draw up a brand new vnode tree every time. I will look into this tomorrow.

**Comment by nunocastromartins** [comment]
There is actually another (much simpler) option; I didn't test this, but I'm confident something like this _should_ work (I believe Snabbdom never clones the `children`):
```js
let list  = h('ul', [h('li', {id: 1}, 'hello'), h('li', {id: 2}, 'world')])

list.children[0] = patch(list.children[0], h('li', {id: 1}, 'goodbye'))
```
Downsides: you're directly manipulating the `children` array, so you'll have to keep track of the index of the element you wish to mutate.

I'm unaware of any other downsides (except that it _feels_ hacky); someone with a fresher memory of the source code might provide a couple more. :-)

**Comment by caridy** [comment]
what I normally do is the following:

```
let list = h('ul', [
  h('li', {id: 1}, 'hello'),
  h('li', {id: 2}, 'world')
])

const cachedVNode = list.children[0];
const oldVNode = Object.assign(cachedVNode);
Object.assign(cachedVNode, h('li', {id: 1}, 'goodbye'));
patch(oldVNode, cachedVNode);
```

Of course, this only work if the new vnode created by calling `h` has the same shape as the previous one, including key, sel, etc. As a side effect, you're mutating the original vnode (cachedVNode), and its corresponding elm from the DOM, so anyone holding a ref to it will diff correctly in a separate tick. But as you can see, this is not pretty, and it is still tricky, e.g.: if the new h does not have children, and the old one has children, you will have to set children to an empty array, otherwise it will keep the old ones in the DOM. We get away with all this in our internal implementation because we have a very restrictive shape for things that can be rehydrated in a separate fiber.

**Comment by wbern** [comment]
Hi guys.

I'm still having trouble getting this to work well in my case. I have complex trees and the only way I find to be able to fix this is to generate new children all the way down to the component that has changed. I can leave other children unchanged in the tree.

It feels like I'm left with a couple options.
* Ask for an enhancement request for Snabbdom, for a feature I'm not myself sure how it can be implemented.
* Do deep-cloning. Not sure what the performance loss is.
* Re-render each component down to the bottom component that requested the update in my lifecycle engine.

Right now I am using the last option, but it feels really wasteful to re-render components that should theoretically not have changed at all (except for the child at the very bottom of its children tree).

**Comment by wbern** [comment]
New thought.

snabbdom uses hooks for all sorts of things, maybe this is the way to go?

Would snabbdom allow me to pass an element with tag "MyComponent", and let me "resolve it" with a hook to actual html (<div>'s etc.)?

So say I pass this to snabbdom's patch method:

```
<div>
  <MyComponent>
    <p>Some text</p>
  </MyComponent>
</div>
```

Would a hook let me "resolve" it to the below?

```
<div>
  <div>
    <h1>MyComponent</h1>
    <p>Some text</p>
  </div>
<div>
```

If this is possible, I may have under-estimated the power of snabbdom. 😄

**Comment by nunocastromartins** [comment]
> Would snabbdom allow me to pass an element with tag "MyComponent", and let me "resolve it" with a hook to actual html (\<div\>'s etc.)?

I don't think you can do this with hooks. 😞

> Right now I am using the last option, but it feels really wasteful to re-render components that should theoretically not have changed at all (except for the child at the very bottom of its children tree).

Rerendering these components _should_ be fast, exactly because the patching algorithm will figure out that nothing has changed; it will only effectively rerender (in the DOM) the child that changed.

Maybe you should provide us a more concrete example so that we can figure out why you're having performance issues.

**Comment by wbern** [comment]
@caridy your thoughts on passing custom "unresolved"  components (eg. <MyComponent>) and resolve them inside snabbdom hooks (aka modify the vnode inside the hook to regular html elements)? Will the snabbdom code crash and burn or is this what I *should* have been thinking from the start?

**Comment by caridy** [comment]
@wbern that's a no go for me. I will recommend you to look at web components, specifically web components semantics / shadow-dom etc. You can probably barrow some ideas from that and apply it to a `thunk`-like implementation in snabbdom. Essentially, you need to make a cut in the fiber of components, so you always render and patch until that cut, and while patching the node that makes the cut, you can decide if (based on some internal state) you need to patch its internals.

I know, I know... a lot of words and a little to hold onto, but this is not a trivial problem. I don't think you will be able to solve it if you don't introduce some sort of stateful vnode that can rely on the diffing algo to determine how to process and patch its internals based on its own state.

**Comment by wbern** [comment]
Hi @caridy. I think what you're saying makes sense.

In the end, I don't think I need to integrate that tightly with Snabbdom for custom components. Granted, it takes a bit of wits to do some sort of pre-processing prior to letting Snabbdom generate content on the page, but it is possible with your own JSX-generator that wraps `snabbdom-pragma`.

Closing this issue, thanks for the input everyone.

**Comment by grimalschi** [comment]
It can be very simple

```
function partialPatch(vNode, newVNode) {
    return Object.assign(vNode, patch(vNode, newVNode))
}
```
