### ISSUE TITLE
Rollup can't import Snabbdom

### ISSUE THREAD

**Issue by rbiggs** [snabbdom/snabbdom#319]
I've been trying to use this with Rollup. I installed it in a project with `npm`. I'm using syntax like this:

```js
import {snabbdom} from 'snabbdom'
```
But Snabbdom never gets included in the final bundle. I also tried the following, to no avail:
```js
import {init, h} from 'snabbdom'
```
 I notice all the examples are using CommonJS `require`. Is it possible to load this as ES6 modules? If so, are there some working examples somewhere?

**Comment by mightyiam** [comment]
The first snippet should not work. The second should (at least according to the code in master).

Do you get an error?

**Comment by rbiggs** [comment]
Yup, neither of the above resulted in anything getting included in the bundle by Rollup. I use Rollup everyday. But this is a first for me. I've never had a problem before where it couldn't import and bundle an NPM module.

**Comment by mightyiam** [comment]
Do you get some sort of error or warning?

**Comment by rbiggs** [comment]
Only in the browser where it says it can find snabbdom or h, etc. That's because they never get bundled. I use rollup all the time for all kinds of projects, so I know this behavior isn't normal. I've never run into this problem with anything before. You're using a UMD format for the module, right?

**Comment by caridy** [comment]
This is a common problem with rollup when the compiled bundle is ambiguous. We have been battling the same thing, and we have tried to fix it via https://github.com/snabbdom/snabbdom/pull/247, but we have no traction on that PR at the moment. Basically, Rollup will check if the CJS has a `default` export or not to try to understand the shape of the package. In the case of snabbdom, the `exports` object is ambiguous due to the double exports everywhere.

**Comment by rbiggs** [comment]
So that means as it stands, Snabbdom is incompatible with Rollup and that may never be resolved. That sucks. I use Rollup for all my projects for code splitting and bundling ES6 modules. I suppose Snabbdom works with Webpack, but I really don't like using it. I prefer Rollup.

**Comment by caridy** [comment]
@rbiggs we will solve it... we just need to keep working on a viable solution considering that all solutions will probably be non-backward compatible, but that should not be a deal breaker.

**Comment by rbiggs** [comment]
Great. Keep me updated on this thread if you make any progress. I'd like to incorporate Snabbdom into some projects, but lack of support for Rollup is a deal-breaker for me.

**Comment by rbiggs** [comment]
Um, that is usually indicated by an appropriate version bump to show that there are breaking changes. That's why NPM uses semver.

**Comment by rbiggs** [comment]
What I'm seeing is the following error in the browser:
```sh
[Error] ReferenceError: Can't find variable: exports
	(anonymous function) snabbdom.js:2
```
Which is pointing to this:
```javascript
Object.defineProperty(exports, "__esModule", { value: true });
```

**Comment by caridy** [comment]
can you create a very small project somewhere to showcase the issue?

**Comment by StreetStrider** [comment]
@caridy, great thanks for your workaround, that helps me alot.
I must notice that there is a little vacuum here for people who using ES6 modules, but not using TS. You can't use origin `.ts` files, since you're not in TS world, but processed files are already transpiled and may be ambiguous for Rollup. I believe, good solution would be to create additional es6 target (ts → es6), which would rid of all the typedefs but still be in ES6 modules syntax.

Anyway, workaround is just working, and I'm OK until it is so. Have nothing against TS, just not using it in every project.

**Comment by rbiggs** [comment]
From my own experience using ES6 modules and Mobx I came to the same conclusion. It would be so much easier to just import the parts you want from Mobx if there were proper ES6 exportable modules the same as there are TypeScript ones.

**Comment by kuraga** [comment]
But even `'snabbdom/es'` are not compatible with ESM... Because of `.js` extensions instead of `.mjs`. Thus it works for Rollup but doesn't work for native NodeJS...

**Comment by mightyiam** [comment]
Assuming this is due to #523 and closing in favor of it.
