### ISSUE TITLE
Document role of the `sel` property in comparison

### ISSUE THREAD

**Issue by lescientifik** [snabbdom/snabbdom#333]
Hi everyone,

I was looking through the source code of snabbdom, and I think the sel properties of a vnode should be more detailed in the documentation.

Indeed, one would want to use this sel properties as a shorthand for adding a class or an id to a vnode. However in the current implementation, despite the fact it is indeed a shorthand for doing that, it is also  a shorthand for setting a key-like property on this vnode (according to sameVnode function).

the same Vnode function:

```javascript
function sameVnode(vnode1: VNode, vnode2: VNode): boolean {
  return vnode1.key === vnode2.key && vnode1.sel === vnode2.sel;
}
```
Example :

```javascript
var a = h("div#myDiv", ["This is a (slightly) hidden keyed div"])
// The selector property of the vnode is "div#myDiv" 
// props object will not exist nor contain reference to the id property

var b = h("div", {props: {id: "myDiv"}}, ["This is a simple div with same id as a"])
// The selector property of the vnode is "div" 
// The props object does contain a reference to the id property

patch(document.body, a)
patch(a, b)  // Triggers remove/destroy hook on a, and insert hook on b
```

That was confusing for me, and probably for other people too (like those coming from Mithril).

It is probably a wanted behavior, but it should be made more explicit in the documentation.

**Comment by caridy** [comment]
@lescientifik feel free to take the first stash at this, and send us a PR.

additionally, we have been debated (in few other open issues), whether or not we want to continue supporting `#` and `.`, or provide a different way to define that, specially because of the `is` attribute which is not considered today in the patching process, and also the possible customization of the `sameVnode()` logic. It might very well be that we can do some more reforms around this.

**Comment by paldepind** [comment]
#1098 adds documentation for this.
