### ISSUE TITLE
props module overwrites selector classes

### ISSUE THREAD

**Issue by jvanbruegge** [snabbdom/snabbdom#353]
When you use the `className` attribute of the props module together with class names on the `sel`, the `className` overwrites the `sel`. I'm currently trying to fix this issue

Version used: 0.7.0

Reproducing example: https://www.webpackbin.com/bins/-L0F6e3MG7nLZM7AjquG
```js
import { h, init } from 'snabbdom';

const patch = init([
  require('snabbdom/modules/props').default
  ]);

patch(
  document.getElementById('app'),
  h('div._1', { props: { className: 'something' }}, [])
);

console.log('something: ' + document.querySelectorAll('.something').length); // "something: 1"
console.log('_1: ' + document.querySelectorAll('._1').length); // "_1: 0"
```

**Comment by jvanbruegge** [comment]
The easiest fix would be to use `classList` under the hood of `className`.

**Comment by jvanbruegge** [comment]
another possible solution would be to normalize this in `h`

**Comment by caridy** [comment]
Yes, producing the right vnode is the way to go here, whether that's the `h` that we provide, or your own custom `h` that apply extra rules.

**Comment by paldepind** [comment]
In my opinion, this is expected behavior. The `props` module is very simple. It sets properties in a way that is identical to manually setting properties on elements.

The reported behavior is what setting the `className` property of an element does. It overwrites existing classes. That's the way the DOM works.

What #354 does is special casing on the `className` property and doing something that is distinctly different from what manually setting `className` on an element would do. IMO that is not the job of the `props` module and it detracts from the transparency of `props`.

I see two things that we should probably do:

1/ Document `props` better so that people can know what to except.
2/ Find a way to give you the behavior you want in a way that doesn't change `props`.

**Comment by jvanbruegge** [comment]
I agree, I think documenting this behavior would be good. This just suprised me, beause the `sel` was set by a library (Cycle.js) and not me, which indirectly lead to my code not emitting events any more.
Having a small wrapper around `h` or (what I am currently doing) removing the library code that adds stuff to the `sel` is the way to go here I think.
