### ISSUE TITLE
Need to npm publish more often

### ISSUE THREAD

**Issue by AlexGalays** [snabbdom/snabbdom#356]
The last published release is 0.7.0 and was 5 months ago. There are some good things on master (15 commits) that could warrant a release (I'd like to build my app using treeshake'able es6 modules).

Also, pointing to github#master doesn't really work as there are some .gitignored files that are required in the npm package.

Could snabbdom be published every few commits or every month, whichever comes first?

Thanks!

**Comment by caridy** [comment]
Yes, we can certain improve that!

**Comment by paldepind** [comment]
Yes, you are right @AlexGalays. I've just pushed a new release to npm. I'm sick at the moment though so I won't write a proper release note. If one of you would do that it would be nice. I think both of you have the GitHub privilege to do it. Go to [this page](https://github.com/snabbdom/snabbdom/releases) and press "Draft new release" and then follow the pattern of our previous release notes.

To facilitate more frequent releases we could add both of you to the npm package so that you can publish releases.
