### ISSUE TITLE
Input element keep displaying the last user input

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#401]
I have an input element that is rendered as follow:

```html
<input value="123" type="text">
```

The first time the element is rendered it displays `123` but after I enter something in the input and submit, the dom is `patch`ed and the input box is rendered again (that is expected) but this time with the last user input instead of `123`. The DOM still display the above code but the rendered widget has the last user input as value.

I think the problem is that I am mis-using snabbdom somehow, but I don't know what I should do.

TIA!

**Comment by amirouche** [comment]
I think the problem is that the input element keeps its internal state. I has to do with controlled vs uncontrolled elements.

**Comment by mightyiam** [comment]
Could you provide a minimal reproduction please?

**Comment by amirouche** [comment]
I found a [workaround](https://github.com/amirouche/snabbdom-issue401/commit/3d01fb38b3b4c581b757f4ff2e49a8a2925eaac7), let me know what you think.

**Comment by paldepind** [comment]
This is the way the DOM works. An input element stores its current state in its `input` _property_. Setting its input _attribute_ only has an effect when the input element is unmodified. You can check this for yourself by doing the following:

1. Create a simple HTML page with `<input value="foo">`. When you open the page the input will have the content "foo".
2. Open the element in the element inspector and change its attribute manually. The changes will be reflected in the input field.
3. Now type some text in the input field. Note that this change is _not_ reflected in the attribute displayed in the inspector.
4. Then change the attribute again through the inspector. This time the change is _not_ reflected in the input field. This is because the input field has been edited and stores its state in the `value` _property_.

I hope the above makes sense. Unless I'm missing something you should be able to solve your problem by using `props` instead of `attrs`.

The `attrs` and `props` modules are very simple and they correspond directly to `elm.setAttribute("foo", bar)` and `elm.foo = bar`. This simplicity has the side-effect that one has to know a little bit more about how the DOM works compared to many frameworks where they abstract away the differences between attributes and properties. Both approaches have pros and cons. If someone is interested in creating an alternative attributes module that is more "clever" then that would probably be a worthwhile endeavour 😄

**Comment by amirouche** [comment]
> The attrs and props modules are very simple and they correspond directly to elm.setAttribute("foo", bar) and elm.foo = bar. 

I am not enough into DOM API to know about that. By the way, I use snabbdom to avoid writing javascript.

>  If someone is interested in creating an alternative attributes module that is more "clever" then that would probably be a worthwhile endeavour smile

I am not sure what the alternative would do.

I close the issue for the time being as I found a workaround that works in my case.

Thanks.

**Comment by amirouche** [comment]
For the time being, I do not expose props in my experiment. I don't how bad it is.

**Comment by cornerman** [comment]
@amirouche We had a similar problem and went for comparing the property value to the dom instead of the VDom in the property module. We discussed the issue here: https://github.com/snabbdom/snabbdom/issues/345.

We only use the property module for a few selected properties like `value`, `checked` 
 and `selected`. So, the overhead should be minimal.

**Comment by pskdreampay** [comment]
@amirouche your workaround link is not working. Can you please provide the solution as I am facing the same issue where the input is persisting the inputted value even if I pass the required value in props.

**Comment by amirouche** [comment]
@pskdreampay sorry I deleted the repo.
