### ISSUE TITLE
Fixing out of sync virtual dom

### ISSUE THREAD

**Issue by fdietze** [snabbdom/snabbdom#412]
In my library I'd like to support dom-manipulations by other js-libraries which are not aware of the virtual dom. When another patch comes in, dom-manipulations should be removed by the patch. I always know when external changes happen, so I can do something different than just `patch(oldVNode, newVNode)`.

My first attempt was:
```javascript
patch(snabbdom.tovnode(oldVNode.elm), newVNode)
```
This allows for external modifications, but has some issues.
Since the vnode created by `tovnode` is not a result of a patch-operation of `oldVNode`, the patch replaces the whole tree, and no dom elements are reused.

Not reusing dom elements does not seem to be bad at first, but it affects scrolling of nested lists and does not keep text which was written in input fields.

Is there a way to make `patch` reuse the old elements?

**Comment by mightyiam** [comment]
I'm curious as to how you ended up with such code where multiple libraries manipulate the same DOM tree.

I imagine the common multiple-library use-case to be one where certain specific subtrees are managed by other libraries, such as a data-visualization library creating graphs in an otherwise snabbdom tree.

For such use cases, the hooks should be enough, I suppose.

Is your use case different in principal to the one I have described above?

**Comment by fdietze** [comment]
Yes the use-case is different. For d3 I'm using an empty node with hooks. That works well.

But for a library like shopify/draggable, which changes the order of a list of nodes the approach with hooks is not applicable.

**Comment by mightyiam** [comment]
I suspect that what you might consider doing is looking into the API of
what I assume to be a drag-n-drop DOM library and seeing whether it can
refrain from performing the DOM changes and instead only provide you with
information on the user's attempt so that you could handle the DOM
manipulation yourself, with snabbdom.

**Comment by fdietze** [comment]
I agree, Ideally this would be the right thing to do. Sadly I don't have the resources to maintain forks of these libraries. Therefore I was looking for another way to make things compatible.

A function to repair the dom according to a vnode could already do the trick.

Then one could write something like:
```
repairdom(oldVNode)
patch(oldVNode, newVNode)
```

**Comment by mightyiam** [comment]
I took a short look but found the documentation too verbose and wasn't sure where to start looking. I'm talking about the draggable docs. I would not be surprised if it is possible through the API to cancel the DOM manipulation and do it yourself like I have described.

**Comment by fdietze** [comment]
I actually got my hands dirty and implemented a function to repair the dom. It was actually quite simple and works for my use-case:

The implementation is written in Scala, but should be readable for js-people as well:
https://github.com/OutWatch/outwatch/pull/279/commits/e11a9a20f44a9ff68f87c774c16fb1a25fe24db1#diff-c9861bd94ad726cd8e09d043cd3eb172R241

There might me some corner-cases I forgot. If you know one, please tell me.
