### ISSUE TITLE
children isn't removed on parent patch

### ISSUE THREAD

**Issue by eguneys** [snabbdom/snabbdom#440]
```
vnode = patch(container, view(ctrl));
function render() {
  vnode = patch(vnode, view());
}

var list = [1, 2, 3, 4];

// view
function view() {
  return list.map(i => {
    return h('div.hand' [
      if (i < 2) {
        h('div.card', style: {
          transition: 'opacity .3s',
          remove: { opacity: '0.2' }
        });
      }
    ]);
  });
}

// model
list.slice(1, 1);
render();
list = [1,2,3,4];
render();
```

when I do something like this I can get a dom like this:

```
<div class="hand">
    <div class="card" style="opacity: 0.2"></div>
   <div class="card" style="opacity: 0.2"></div>
   <div class="card"></div>
</div>
```

there are some `card` divs that aren't removed from the dom.

if I do this it works fine:
```


list.slice(1, 1);
render();
list = [];
render();
list = [1,2,3,4];
render();
```

**Comment by paldepind** [comment]
I can't see exactly what your render function is doing, but, I think this is because you are reusing vnodes between patches. By slicing the array of vnodes and reusing it you are giving Snabbdom the same vnodes twice. Please see this for a bit more information: https://github.com/snabbdom/snabbdom#common-errors.

**Comment by eguneys** [comment]
I am slicing the model to generate vnodes. vnodes are created from scratch from the model on each render. see my edit please.

**Comment by eguneys** [comment]
I finally reproduced the issue https://jsfiddle.net/eguneys/4La92dcm/35/

**Comment by filosganga** [comment]
@eguneys Did you manage to solve/workaround the issue? I am experiencing the same

**Comment by mightyiam** [comment]
I looked into your example and it's a bit too complicated. Could you simplify it somewhat so that it's the minimum necessary to reproduce the issue, please?

Here's a version of your example that is only slightly simpler and is hosted in CodePen:
https://codepen.io/mightyiam/pen/xxVdMYL?editors=0010

Since this is such an old issue, I'll close it and if you still happen to care about it, then please do comment.
