### ISSUE TITLE
Get more active maintainers so future of snabbdom is not blocked on @paldepind

### ISSUE THREAD

**Issue by nojvek** [snabbdom/snabbdom#462]
It seems @paldepind has gone AWOL and PRs have been stuck for months now. e.g #451 

Raising some alarm bells that this doesn't look very good for a production grade open source project. 

Would love to see this project get the love and care that it deserves. We should get more active maintainers and not be blocked on one person. Well run projects are usually democracies with a healthy community.

**Comment by mightyiam** [comment]
> I've been very busy with a deadline for the 1st of november.

Good luck!

> Would you (@nojvek) like to be a maintainer?

I second that!

> @mightyiam has been doing a great job. If I continue to be a bottleneck we could very well let him merge PRs on his own. But, it would definitely be preferable to have several maintainers to look at and approve PRs.

Thank you! :heart:

:+1: for more maintainers, definitely!

**Comment by nojvek** [comment]
> I apologize for the radio silence. I've been very busy with a deadline for the 1st of november.
> 
> To be fair Snabbdom is a mature and stable project. There has not been any major changes in years. It definitely needs maintenance but nothing critical.

I’m with you here. I’m one of the senior front-end devs at Mixpanel and we’ve depended on this nimble but powerful library for a while now. 

But for any active open source project, I guess the chores are somewhat ongoing. Better documentation/tutorials. Keeping tests coverage high and keeping them green. Triaging issues and PRS. Guiding PRs and helping them land. I’m sure you know the deal. 

I’m super grateful for all you’ve done. Open source doesn’t pay the bills and we all gotta earn our bread somehow so I understand active maintainers being inactive for a while. 

> Would you like to be a maintainer? Snabbdom has several maintainers, but lately many of them has been inactive and I am often inactive as well. @mightyiam has been doing a great job. If I continue to be a bottleneck we could very well let him merge PRs on his own. But, it would definitely be preferable to have several maintainers to look at and approve PRs.

@mightyiam has indeed been great. His desire to fully understand things deeper is an admirable quality. I also respect his ideas on architectural decisions. 

I wouldn’t mind being a contributor if that’s okay with you. 

Regarding merging, we could make it a policy that two maintainers need to give a 👍for substantial PRs and all existing parties to the conversation should be satisfied with the implementation.

**Comment by kuraga** [comment]
Thanks to everybody! My fifty cents: current issues (architecture issues but not hard-bugs only) IMHO is more important than new features.

**Comment by paldepind** [comment]
> I wouldn’t mind being a contributor if that’s okay with you.

Amazing. I've sent you an invite to become a member of the Snabbdom organization.

Here's what I propose going forward:

1. For PR's regarding maintenance, documentation, configuration-related things (CI, linting, updating dependencies) two maintainers should approve. Since @mightyiam is currently the most active maintainer he can also merge such PR's if no other maintainer has responded in a week. I may also merge such PRs on my own.
2. Bug fixes are treated similarly to the above.
3. For more substantial PR's involving new code, etc. both I and @mightyiam must approve the PR.

This means that no single maintainer will be a bottleneck except for in case 3. Given the current number of maintainers I think that is the best solution.

**Comment by jvanbruegge** [comment]
Great to see this going :+1:
snabbdom is a vital dependency of cyclejs and while I am happy to fix bugs I encounter, having a group of people that may merge is definitely a good thing to get such bug fixes to all users quickly.

On that note, maybe @mightyiam wants to tests his new npm rights to publish the fix for FF70 @paldepind merged a few hours ago? :sweat_smile:

**Comment by mightyiam** [comment]
@jvanbruegge after going through the commits since the last release, I have determined that it is a patch bump. And so I've bumped the version in #477 and now I just require the npm permission to publish.

**Comment by jvanbruegge** [comment]
@paldepind @mightyiam what's the status of the npm access? The latest version is still 0.7.3 without my patch

**Comment by mightyiam** [comment]
I apologize, @jvanbruegge. I didn't get it, yet. #492 .

**Comment by nojvek** [comment]
@paldepind if it’s okay with you, I vote for @mightyiam to get npm access too. 

Policy remains same. All major PRs / releases will need for be signed off by you and someone else.

But for minor and patch fix/ releases I think it makes sense for us to move at a faster pace.
