### ISSUE TITLE
Number input not using value properly.

### ISSUE THREAD

**Issue by delaneyj** [snabbdom/snabbdom#53]
Using snabbdom-cerebral and running into some issue that appear to be snabbdom related.

Here is the jsx markup
`<input type="number" on-change={signals.test} value={state.test||5}/>`

and here is how the `state.test` object is getting set
```jsx
controller.signal('test', [
  ({input,state})=> {
    const int = parseInt(input.target.value);
    const bounded = Math.max(2,Math.min(16,int));
    state.set('test',bounded);
  }
]);
```

If you console.log before the input renders you will see that the `test.state` does in fact stay between 2-16 (inclusively) but the input has no such bounds.  I know in this case I could use `min=2 max=6` on the input but this is a simplified version of more elaborate constraints.  

Is this a snabbdom issue related to on-change of inputs?

**Comment by paldepind** [comment]
The `input` is getting a value that is outside the range [2;16]. Is that correctly understood?

I'm guessing that the value of the input isn't being set after the user has typed in it. But that is just a guess.

**Comment by delaneyj** [comment]
@paldepind if I put a console.log(state.test) it will show the value go from 5,4,3,2,2,2,2 as I click down on the input arrow the value in the control goes 5,4,3,2,1,0,-1.  Does that make sense?

**Comment by kay999** [comment]
The reason is, that snabbdom only compares props from the vdom, not from the actual element values. So if the value reaches 2, snabbdom sees no changes anymore and thus doesn't update the control. But the control value is still changed by the user so the bound isn't in effect.

The same happened to me: I tried to do "input normalization" on certain fields (removing leading/trailing spaces) which wouldn't work for the same reason: The user changes the input, but snabbdom doesn't see a difference, becaus the vdom-elm-value isn't changed.

Now snabbdoms approach to only compare vdom-prop-values is very fast and in most cases correct, but in certain cases it leads to problems. So I created a simple plugin based on "props" for those cases:

`function updateProps(oldVnode, vnode) {
  var key, cur, old, elm = vnode.elm,
      props = vnode.data.liveProps || {};
  for (key in props) {
    cur = props[key];
    old = elm[key];
    if (old !== cur) elm[key] = cur;
  }
}

module.exports = {create: updateProps, update: updateProps};
`

Now by useing "liveProps" instead of props for this kind of problems, everything works fine...

**Comment by AlexGalays** [comment]
@kay999: Cheers for the code, works fine except it should also delete the key if the value becomes nullsy.

For info, virtual-dom fixed this issue with a similar mechanism:  https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/index.js#L50

Perhaps this can be closed now?
