### ISSUE TITLE
mightyiam stepping down

### ISSUE THREAD

**Issue by mightyiam** [snabbdom/snabbdom#868]
I am stepping down from maintaining this project. It's been a constructive experience and I hope I helped.

**Comment by kuraga** [comment]
@mightyiam , thank you very much! The project got a new life thanks to you and all of you!

**Comment by mreinstein** [comment]
Is there any info on who is picking up maintainer ship?

**Comment by jvanbruegge** [comment]
@paldepind I would be up to do some maintainership, but I hope there are others that would help me

**Comment by mreinstein** [comment]
@jvanbruegge I would be willing to help. I don't have much knowledge of snabbdom internals but I'm sure I can pick it up.

**Comment by jvanbruegge** [comment]
Yeah, I don't expect that much maintenance work, snabbdom is pretty good already. I'd just like to be in the position to ne able to fix bugs that crop up during Cycle.js development

**Comment by mreinstein** [comment]
> I don't expect that much maintenance work

Sure, it works pretty good. I'm using it in my full time day job. But it also has a lot of problems and the issues are piling up.

**Comment by jvanbruegge** [comment]
Yes, I want to at least redo (slim down) tooling and fix packaging (#913)

**Comment by mreinstein** [comment]
that would be fantastic. The fact that snabbom doesn't have a default export is a little silly, as that's typicallythe first thing people try when integrating a new module. `import snabbdom from 'snabbdom'` ideally would work.

Also, I don't know if I'm alone on this, but I'm kind of lamenting the general state of snabbdom in terms of over-engineering. I understand the value typescript brings, but it has made the source code much harder to read. The automated tooling, while nice on paper, has generated a lot of ticket noise.

**Comment by jvanbruegge** [comment]
@paldepind for the tooling stuff, I probably need owner access or however it is called to disable renovate and configure secrets for CI

**Comment by paldepind** [comment]
I didn't see this until now. Thanks a lot for your work @mightyiam during your time as a contributor. It is highly appreciated. What do you think should happen to the [open collective](https://opencollective.com/snabbdom#section-contribute)? To me it doesn't seem like it makes much sense to keep open.

@mreinstein and @jvanbruegge. I'm happy to hear that you would like to help maintain Snabbdom. As always, maintainership is very non-commital and I'll be happy to give you the necessary rights as you're both known and trustworthy. I am not doing much, but sometimes I see things (but as of late a lot of Snabbdom emails have been drowning in my inbox amongst all the renovate PRs).

@jvanbruegge Please let me know what kind of rights you need in order to disable renovate. Etc.

As for the other suggestions in this thread please open separate issues 😃

**Comment by mightyiam** [comment]
I'm willing to help whoever wishes to take over.

**Comment by mreinstein** [comment]
btw thanks for all of your help maintaining snabbdom!

**Comment by jvanbruegge** [comment]
@paldepind I need to be able to change the repo settings

**Comment by mightyiam** [comment]
I'm doing some maintenance.

**Comment by mightyiam** [comment]
I'll keep doing maintenance.

**Comment by mightyiam** [comment]
@mreinstein please be specific. I'll try to help resolve all issues that you care about.

**Comment by mreinstein** [comment]
will open a new ticket, because this one is closed, and it's not my intention to "go after" anyone.

**Comment by mightyiam** [comment]
@paldepind @jvanbruegge I'd like to transfer admin-ship of the Open Collective to someone. There is already a pending invitation for @jvanbruegge there. Let me know what to do. The invite is based on Open Collective user names.

**Comment by jvanbruegge** [comment]
I do not see an invitation, on Open Collective my username is `janvanbruegge`

**Comment by mightyiam** [comment]
> I do not see an invitation, on Open Collective my username is `janvanbruegge`

Sent.
