### ISSUE TITLE
feature request: update to esm modules

### ISSUE THREAD

**Issue by iambumblehead** [snabbdom/snabbdom#963]
This script but it isn't valid esm https://cdn.jsdelivr.net/npm/snabbdom@3.0.1/build/h.js
```javascript
import { vnode } from "./vnode";
// should be as below
import { vnode } from "./vnode.js";
```
Please update this package to export esm as well.

If you are accepting PRs, I would be willing to try making a PR for this.

**Comment by iambumblehead** [comment]
If I try to load this script https://cdn.jsdelivr.net/npm/snabbdom@3.0.1/build/snabbdom.cjs.min.js
```javascript
Uncaught ReferenceError: exports is not defined
```

Snabbdom cannot be used in a browser without being transformed

**Comment by jvanbruegge** [comment]
`snabbdom` is already in es modules, an apparently skypack should work:
```
import { h } from 'https://cdn.skypack.dev/snabbdom'
```

**Comment by mreinstein** [comment]
I'm re-opening this issue because it's not really resolved.  Yes, skypack does provide a way to import snabbdom as an esmodule, but only because it parses our repository and fixes the problem of no file extension being present on any of the imports in `build/*.js`.  We do not generate valid javascript modules by default.

When this issue was first opened 2 years ago the node/browser ecosystem didn't have the level of support that it does now.  All browsers and supported versions of node natively handle ESM now. We should fully adopt it and not need to rely on a 3rd party service like skypack to un-break what we've published to npm.
